#!/bin/bash -e

SCRIPTS=`dirname $0`
if [ "$SCRIPTS" != "scripts" ] ; then
  echo "mkimage must be run from deployer-website dir"
  exit 1
fi

rm -rf IMAGE
mkdir IMAGE
mkdir -p IMAGE/css/deployer
cp -r css/deployer/* IMAGE/css/deployer
mkdir -p IMAGE/js/deployer
cp -r js/deployer/* IMAGE/js/deployer
# TODO: just commented out for efficiency reasons ...
# mkdir -p IMAGE/downloads/current
# cp current/* IMAGE/downloads/current
# TODO: also copy to some version of yyyy-mm

rm -rf parts
mkdir parts
for i in content/* ; do
  if [ -d $i ] ; then
    dn=`basename $i`
    mkdir parts/$dn
    for j in $i/* ; do
      bn=`basename $j`
      scripts/spliceInto $j > parts/$dn/$bn
    done
  else
    bn=`basename $i`
    scripts/spliceInto $i > parts/$bn
  fi
done

scripts/assemble layout/page.html > IMAGE/deployer_website.html
