#!/bin/bash -e

SCRIPTS=`dirname $0`
if [ "$SCRIPTS" != "scripts" ] ; then
  echo "mkimage must be run from deployer-website dir"
  exit 1
fi

rm -rf IMAGE
mkdir IMAGE
mkdir IMAGE/css
cp css/* IMAGE/css
# TODO: just commented out for efficiency reasons ...
# mkdir -p IMAGE/downloads/current
# cp current/* IMAGE/downloads/current
# TODO: also copy to some version of yyyy-mm

rm -rf parts
mkdir parts
for i in content/* ; do
  bn=`basename $i`
  scripts/spliceInto $i > parts/$bn
done

cp -r js IMAGE
scripts/assemble layout/page.html > IMAGE/index.html
