#!/bin/bash

awk '
BEGIN { mode = "COPY" }
mode == "SETFILE" {
  readfrom = $0
  mode = "COPY"
  lineNumber = 1
  next
}
mode == "INSERT" {
  printf "<div class='codeblock'>\n"
  readUntil = $0
  while (1) {
    if (pushBack) {
      inputLine = pushBack
      pushBack = ""
      status = 1
    } else {
      status = getline inputLine < readfrom
    }
	if (substr(inputLine, 1, length(readUntil)) == readUntil) {
	  pushBack = inputLine
	  break
	}
	printf "<div class='codeline'><span class='codelineno'>%d</span><span class='codelinetext'>%s</span></div>\n", lineNumber++, inputLine
    if (status != 1) {
      close(readfrom)
      break
	}
  }
  printf "</div>\n"
  mode = "COPY"
  next
}
$0 == "%readfile" { mode = "SETFILE" ; next }
$0 == "%segment" { mode = "INSERT" ; next }
mode == "COPY" { print ; next }
{ print "INVALID MODE", mode}
' "$@"
